# $schema: https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json

- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - amazon.aws.ec2_metadata_facts:

  - community.general.sudoers:
      name: github-actions-runner
      user: runner
      commands: ALL

  # TODO: Avoid hard-coding version
  # TODO: Checksum
  - ansible.builtin.unarchive:
      dest: /home/runner/actions-runner
      owner: runner
      group: runner
      remote_src: yes
      src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-{% if ansible_architecture == "x86_64" %}x64{% else %}arm64{% endif %}-2.317.0.tar.gz

  - ansible.builtin.command: ./bin/installdependencies.sh
    args:
      chdir: /home/runner/actions-runner

  - ansible.builtin.command: ./config.sh --url {{ url }} --token {{ token }} --ephemeral --disableupdate --labels drakon64/github-actions-runner-aws,EC2-{{ ansible_ec2_instance_type }}{% if spot %},EC2-Spot{% endif %},EBS-{{ ebs_volume_size }}GB
    args:
      chdir: /home/runner/actions-runner
    become_user: runner

  # TODO: Run as a oneshot service
  - ansible.builtin.shell: ./run.sh &
    args:
      chdir: /home/runner/actions-runner
    become_user: runner
