# $schema: https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json

- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - amazon.aws.ec2_metadata_facts:

  - ansible.builtin.template:
      src: tag.sh.j2
      dest: /home/runner/tag.sh
      owner: runner
      group: runner
      mode: 0700

  - ansible.builtin.command: ./config.sh --url {{ url }} --token {{ token }} --ephemeral --disableupdate --labels drakon64/github-actions-runner-aws,EC2-{{ ansible_ec2_instance_type }},EBS-{{ ebs_volume_size }}GB
    args:
      chdir: /home/runner/actions-runner
    become_user: runner

  # TODO: Run as a oneshot service
  - ansible.builtin.shell: ./run.sh &
    args:
      chdir: /home/runner/actions-runner
    become_user: runner
