# $schema: https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json

- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - amazon.aws.ec2_metadata_facts:

  - ansible.builtin.apt:
      deb: https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/arm64/latest/amazon-cloudwatch-agent.deb

  - ansible.builtin.copy:
      src: amazon-cloudwatch-agent.json
      dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
      owner: cwagent
      group: cwagent
      mode: 0644

  - ansible.builtin.systemd_service:
      name: amazon-cloudwatch-agent
      state: restarted

  - ansible.builtin.user:
      name: runner
      create_home: yes

  - community.general.sudoers:
      name: github-actions-runner
      user: runner
      commands: ALL

  - ansible.builtin.file:
      path: /home/runner/actions-runner
      state: directory
      owner: runner
      group: runner

  # TODO: Avoid hard-coding version
  # TODO: Checksum
  - ansible.builtin.unarchive:
      dest: /home/runner/actions-runner
      owner: runner
      group: runner
      remote_src: yes
      src: https://github.com/actions/runner/releases/download/v2.316.1/actions-runner-linux-arm64-2.316.1.tar.gz

  - ansible.builtin.template:
      src: tag.sh.j2
      dest: /home/runner/tag.sh
      owner: runner
      group: runner
      mode: 0700

  - ansible.builtin.command: ./bin/installdependencies.sh
    args:
      chdir: /home/runner/actions-runner

  - ansible.builtin.command: ./config.sh --url {{ url }} --token {{ token }} --ephemeral --disableupdate --labels drakon64/github-actions-runner-aws,EC2-{{ ansible_ec2_instance_type }}
    args:
      chdir: /home/runner/actions-runner
    become_user: runner

  - ansible.builtin.copy:
      dest: /home/runner/actions-runner/.env
      content: ACTIONS_RUNNER_HOOK_JOB_STARTED=/home/runner/tag.sh
      owner: runner
      group: runner
      mode: 0600

  # TODO: Run as a oneshot service
  - ansible.builtin.shell: ./run.sh &
    args:
      chdir: /home/runner/actions-runner
    become_user: runner
