name: Build and deploy (Canary)

on:
  push:
    branches:
      - canary
    paths:
      - src/**.rs
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get -y install awscli

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}

      - uses: actions/checkout@v4

      - run: pip3 install cargo-lambda

      - run: cargo lambda build --release --arm64 --output-format zip

      - run: aws s3api put-object --body target/lambda/github-actions-runner-aws/bootstrap.zip --checksum-algorithm sha256 --bucket drakon64-github-actions-runner-aws-artifacts --key canary.zip
