name: Nix
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: github-actions-runner-aws
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build --cores 1 --max-jobs 4
